### ISSUE TITLE
Lock Pro

### ISSUE THREAD

**Issue by dackel1** [sblibs/pySwitchbot#248]
Since Update to HA Core 2024.9 the function to "pull the latch" (german: Falle ziehen) is missing. 
Before the update: On the dashboard it was possible to lock and unlock AND to open the door - this function was great. HA even asked on first tap: "really want to open". 
Since the update to 2024.9 the functions are limited to lock and (unlock&open). 
The "old" behaviour was much better, worked flawless and was much more safe - it was nearly impossibility to remote OPEN the door by accident. 
Please restore the old behaviour.

**Comment by Michal4K** [comment]
Yeh, this library now has disabled nightlatch detection... on purpose as the detection was not working properly. There will be work around for this which will allow you to force nightlatch in HomeAssistant. Unfortunately this change didn't make it into the 2024.9...

**Comment by Michal4K** [comment]
for now you can fix it by updating pySwitchbot lib to my version which has set nightlatch to be always enabled - https://github.com/Danielhiversen/pySwitchbot/pull/245#issuecomment-2251521762

**Comment by dackel1** [comment]
@Michal4K Thank you for your quick reply and the workaround.
Do I understand you right and you want to restore the latch-function in 2024.10? 
As HA beginner I'm not shure how to get back from the workaroud to the release-channel, so waiting for 2024.10 would really be an option.

**Comment by Michal4K** [comment]
Yes, you can wait for 2024.10. When it will be released and you update to it. You will need go to Settings -> Device and Services -> SwitchBot Bluetooth. Then hit configure on your lock entry... there will be checbox with text "Force Nightlatch operation mode".

**Comment by dackel1** [comment]
@Michal4K 
This is great news. Thanks for this information, your work & help.

**Comment by andreasbrett** [comment]
@dackel1 Since the integration works as expected now, could you close the issue?

**Comment by dackel1** [comment]
@Michal4K 
Of course. I'm new to github, sorry
